// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/Canvas.tsx": () => import("../components/mockups/Canvas.tsx"),
  "./components/mockups/SidebarDrawerPicker.tsx": () => import("../components/mockups/SidebarDrawerPicker.tsx"),
  "./components/mockups/SidebarInlineAccordion.tsx": () => import("../components/mockups/SidebarInlineAccordion.tsx")
};
